version: 2.1

common: &common
  working_directory: ~/repo
  docker:
    - image: circleci/node:14.6-browsers
    
commands: # a reusable command with parameters
  Restore-Source-Cache:
    steps:
      - restore_cache:
          keys: 
            - source-{{ .Branch }}-{{ .Revision }}
  Restore-Node-Cache:
    steps:
      - restore_cache:
          keys: 
            - dependency-cache-{{ checksum "package-lock.json" }}

jobs:
  Checkout-Repo:
    <<: *common
    steps:
      # Optimization: Takes advantage of cached data
      - Restore-Source-Cache
      - checkout        # Put in current working directory
      - run: 
          - name: "Manually Clear Git Garbage"
          - command: git gc     #clear git barbage for smaller cache
      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - '.git'
  install:
    <<: *common
    steps:
      - Restore-Source-Cache
      - Restore-Node-Cache
      - run:
          name: "Install packages with yarn"
          command:  yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    <<: *common
    steps:
      - Restore-Cache
      - run:
          name: 'Run Tests'
          command: npm run test
  build:
    <<: *common
    steps:
      - Restore-Cache
      - run:
          name: 'Build app'
          command: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build
            - package.json


workflows:
  version: 2
  Deployment:
    jobs:
      - Checkout-Repo