version: 2.1
jobs:
  build:
    docker:
      - image:  circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello Circle!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That is familiar'
      - run:
          name: Running in a Unique Container
          command: |
            node -v